name: Convert Markdown to HTML

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Convert Markdown to HTML
      run: |
        sudo apt-get install -y pandoc
        find . -name "*.md" -type f -exec sh -c '
          mkdir -p "html/$(dirname "${0}")"
          pandoc "${0}" -f markdown -t html -o "html/${0%.md}.html"
        ' {} \;

    - name: Commit and push HTML files
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add html/
        git commit -m "Convert Markdown to HTML"
        git push
