name: Convert Markdown to HTML

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Convert Markdown to HTML
      uses: BaileyJM02/markdown-to-html@v1
      with:
        input_dir: .
        output_dir: html

    - name: Commit and push HTML files
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add html/
        git commit -m "Convert Markdown to HTML"
        git push
